from pathlib import Path

import pytest

from bin.import_sweep import parse_exported_requirements
from pyutil.env_utils import load_env


def test_import_sweep_smoke_parses_only_direct_dependencies(tmp_path: Path) -> None:
    requirements_file = tmp_path / "requirements.txt"
    requirements_file.write_text(
        "\n".join(
            [
                "# This file was autogenerated by uv via the following command:",
                (
                    "#    uv export --locked --package mega-rag-chatbot "
                    "--group dev --no-hashes --output-file requirements.txt"
                ),
                "aiohttp==3.13.3",
                "    # via mega-rag-chatbot",
                "attrs==26.1.0",
                "    # via aiohttp",
                "pip-audit==2.10.0",
                "",
            ]
        )
    )

    assert parse_exported_requirements(requirements_file) == ["aiohttp", "pip-audit"]


def test_import_sweep_smoke_avoids_substring_false_positive(tmp_path: Path) -> None:
    requirements_file = tmp_path / "requirements.txt"
    requirements_file.write_text(
        "\n".join(
            [
                "# This file was autogenerated by uv via the following command:",
                (
                    "#    uv export --locked --package my-config "
                    "--no-hashes --output-file requirements.txt"
                ),
                "helper-lib==1.0.0",
                "    # via my-config-helper",
                "direct-lib==2.0.0",
                "    # via my-config",
                "",
            ]
        )
    )

    assert parse_exported_requirements(requirements_file) == ["direct-lib"]


def test_load_env_smoke_finds_parent_env_file(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    env_file = tmp_path / ".env.smoke"
    env_file.write_text("SMOKE_TEST_VALUE=ok\n")

    nested_dir = tmp_path / "a" / "b" / "c"
    nested_dir.mkdir(parents=True)

    monkeypatch.chdir(nested_dir)

    loaded = load_env("smoke")

    assert loaded["SMOKE_TEST_VALUE"] == "ok"
