/**
 * Shared template rendering utilities for email templates
 * Provides HTML escaping and template variable substitution
 */

/**
 * Escapes HTML special characters to prevent XSS attacks
 *
 * @param text - Text to escape
 * @returns Escaped HTML string
 */
export function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#039;",
  };
  return text.replace(/[&<>"']/g, (m) => map[m]);
}

/**
 * Renders template variables in a string
 * Escapes HTML in variable values to prevent XSS attacks
 * Note: Variables that contain HTML (like exampleQuestions) should be passed
 * as-is since they're generated by our code, not user input
 *
 * @param template - Template string with {{variable}} placeholders
 * @param variables - Object with variable values
 * @param escapeHtmlValues - Whether to escape HTML (default: true)
 * @returns Rendered string
 */
export function renderTemplate(
  template: string,
  variables: Record<string, string>,
  escapeHtmlValues: boolean = true
): string {
  let rendered = template;
  for (const [key, value] of Object.entries(variables)) {
    const placeholder = new RegExp(`\\{\\{${key}\\}\\}`, "g");
    // Escape HTML unless this is a variable that contains trusted HTML
    // Variables like 'exampleQuestions', 'Html', 'Url' contain HTML generated by our code
    const shouldEscape =
      escapeHtmlValues && !key.includes("Questions") && !key.includes("Html") && !key.includes("Url");
    const safeValue = shouldEscape ? escapeHtml(value) : value;
    rendered = rendered.replace(placeholder, safeValue);
  }
  return rendered;
}
